apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcpo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mcpo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mcpo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mcpo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mcpo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- toYaml .Values.container.command | nindent 12 }}
          args: {{- toYaml .Values.container.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          volumeMounts:
            - name: mcpo-config
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: mcpo-config
          configMap:
            name: {{ include "mcpo.fullname" . }}-config
