apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcpo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mcpo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mcpo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
