apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentzero
  namespace: {{ .Release.Namespace }}
  labels:
    app: agentzero
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agentzero
  template:
    metadata:
      labels:
        app: agentzero
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: agentzero
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          ports:
            - containerPort: 80
      {{- if .Values.persistence.enabled }}
      volumeMounts:
        - name: agentzero-prompts
          mountPath: /a0
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumes:
    - name: agentzero-prompts
      persistentVolumeClaim:
        claimName: agentzero-pvc
  {{- end }}