apiVersion: v1
kind: Service
metadata:
  name: agentzero
  namespace: {{ .Release.Namespace }}
  labels:
    app: agentzero
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: agentzero