
image:
  repository: frdel/agent-zero-run
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "2"
    memory: "4Gi"

env:
  - name: API_KEY_OPENAI
    value: "sk-..."

