apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swiss.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "swiss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "swiss.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ include "swiss.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "swiss.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {{- toYaml .Values.resources | nindent 12 }}
